# Change these first
owner: the1ev234 # Your GitHub organization or username, where this repository lives
repo: status-thermal # The name of this repository
user-agent: the1ev234

sites:
  - name: Thermal
    url: http://thermal.run.place/
    logoUrl: https://raw.githubusercontent.com/tp-link-extender/status/main/Mercury.svg
  - name: Client Setup
    url: http://setup.thermal.run.place/
    logoUrl: https://raw.githubusercontent.com/tp-link-extender/status/main/Mercury.svg
  - name: API
    url: http://thermal.run.place/api/
    logoUrl: https://raw.githubusercontent.com/tp-link-extender/status/main/Mercury.svg
  - name: Asset Delivery
    url: http://thermal.run.place/asset/
    logoUrl: https://raw.githubusercontent.com/tp-link-extender/status/main/Mercury.svg
    expectedStatusCodes:
      - 400

assignees:
  - the1ev234

status-website:
  theme: night
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.thermal.run.place
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/tp-link-extender/status/main/Mercury.svg
  name: Thermal
  introTitle: "Thermal Status"
  navbar:
    - title: Thermal
      href: http://thermal.run.place/
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/the1ev234/status-thermal

i18n:
  footer: "[Thermal](https://thermal.run.place) 2025-2025. This page is [open source]($REPO)."

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
